licensing_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from main import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include(urls, namespace='main'), name='main'),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^free_key_generate/', views.free_key_generate, name='free_key_generate'),
    url(r'^free_key_generate_ajax/', views.free_key_generate_ajax, name='free_key_generate_ajax'),
    url(r'^auth_key_register/', views.auth_key_register, name='auth_key_register'),
    url(r'^auth_key_generate_ajax/', views.auth_key_generate_ajax, name='auth_key_generate_ajax'),
    url(r'^product_license_detail/(?P<product_id>[0-9]+)/$', views.product_license_detail, name='product_license_detail'),
    url(r'^logout/$', views.logout, name='logout'),
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin

# Create your models here.

class AuthUserManager(BaseUserManager):
    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)

class Customer(AbstractBaseUser, PermissionsMixin):
    """
    Used for all authenticated user (influencers, brands, assistants, superuser, etc...)
    """

    first_name = models.CharField( ('first name'), max_length=30, blank=True)
    last_name = models.CharField( ('last name'), max_length=30, blank=True)
    email = models.EmailField( ('email address'), max_length=254, unique=True)
    is_staff = models.BooleanField( ('staff status'), default=False,
                                   help_text= ('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField( ('active'), default=True,
                                    help_text= ('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField( ('date joined'), auto_now_add=True)
    objects = AuthUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __unicode__(self):
        return self.email

    class Meta:
        db_table = 'customer'

class Evaluation_User(models.Model):

    name = models.CharField(max_length=30, db_column="name")
    email = models.EmailField(max_length=254, unique=True, db_column="email")
    company_name = models.CharField(max_length=255, db_column="company_name", default="")
    phone_number = models.CharField(max_length=255, db_column="phone_number", default="")
    license_requirements = models.CharField(max_length=255, db_column="license_requirements", default="")
    interest_product = models.CharField(max_length=255, db_column="interest_product", default="")
    time_frame = models.CharField(max_length=255, db_column="time_frame", default="")
    date_joined = models.DateTimeField(auto_now_add=True, db_column="date_joined")
    is_subscribed = models.BooleanField(default=False, db_column="is_subscribed")
    note_use = models.TextField(db_column="note_use", default="")
    email_activities = models.IntegerField(max_length=11, db_column="email_activities", default=1)

    class Meta:
        db_table = 'evaluation_user'

class Label_License_Requirement(models.Model):

    list_id = models.IntegerField(max_length=30, db_column="list_id")
    name = models.CharField(max_length=30, db_column="name")

    class Meta:
        db_table = 'label_license_requirement'

class Label_Interest_Product(models.Model):
    list_id = models.IntegerField(max_length=30, db_column="list_id")
    name = models.CharField(max_length=30, db_column="name")

    class Meta:
        db_table = 'label_interest_product'

class Label_Purchase_Time_Frame(models.Model):

    list_id = models.IntegerField(max_length=30, db_column="list_id")
    name = models.CharField(max_length=30, db_column="name")

    class Meta:
        db_table = 'label_purchase_time_frame'

class License_Allowance(models.Model):

    product_id = models.IntegerField(max_length=11, db_column="product_id", default=0)
    user_id = models.IntegerField(max_length=11, db_column="user_id", default=0)
    total_product = models.CharField(max_length=30, db_column="total_product", default=0)
    registered_product = models.CharField(max_length=30, db_column="registered_product", default=0)

    class Meta:
        db_table = 'license_allowance'

class License_Registration(models.Model):

    key = models.TextField(max_length=30, db_column="key")
    product_id = models.EmailField(max_length=254, db_column="product_id")
    user_email = models.CharField(max_length=254, db_column="user_email")
    system_hash = models.CharField(max_length=254, db_column="system_hash")
    product_name = models.CharField(max_length=254, db_column="product_name", default="")
    number_licenses = models.IntegerField(max_length=11, db_column="number_licenses")
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)

    class Meta:
        db_table = 'license_registration'

class Product(models.Model):

    name = models.CharField(max_length=254, db_column="name")
    type = models.CharField(max_length=254, db_column="type", default="")

    class Meta:
        db_table = 'product'

main/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms

invalid_error = 'User with this {} already exists.'

class LoginForm(auth_forms.AuthenticationForm):
    username = forms.EmailField(max_length=254,
                               widget=forms.EmailInput(attrs={'class': 'form-control',
                                                             'required': 'Trcue',
                                                              'placeholder': 'Email...'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'required': 'True',
                                                                 'placeholder': 'Password...'}))
    next_ = forms.CharField(widget=forms.HiddenInput())

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from django.template import Context
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.conf import settings

from os.path import expanduser

from .models import *
from .forms import LoginForm

import subprocess
import time
import re

admin_emails = settings.ADMIN_EMAIL_LIST

# Create your views here.c

def login(request):
    redirect_to = request.POST.get('next_',
                                   request.GET.get('next', 'main:auth_key_register'))
    if request.user.is_authenticated():
        return redirect(redirect_to)
    if request.method == "POST":

        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            # Okay, security check complete. Log the user in.
            auth.login(request, form.get_user())
            return redirect(redirect_to)
    else:
        form = LoginForm(request, initial={'next_': redirect_to})

    return render(request, 'pages/login.html', {'form': form})

def logout(request):
    auth.logout(request)
    return redirect('main:login')

def free_key_generate(request):

    license_requirements_list = Label_License_Requirement.objects.all()
    interest_products_list = Label_Interest_Product.objects.all()
    time_frame_list = Label_Purchase_Time_Frame.objects.all()

    context = {
        'license_requirements_list': license_requirements_list,
        'interest_products_list': interest_products_list,
        'time_frame_list': time_frame_list,
    }

    return render(request, 'pages/eval_request.html', context)

def free_key_generate_ajax(request):

    name = request.GET.get('name')
    email = request.GET.get('email')
    company_name = request.GET.get('company_name')
    phone_number = request.GET.get('phone_number')
    note_use = request.GET.get('note_use')
    license_requirements = request.GET.get('license_requirements')
    product_interest = request.GET.get('product_interest')
    time_frame = request.GET.get('time_frame')

    if Evaluation_User.objects.filter(email=email).exists():

        evaluation_user = Evaluation_User.objects.get(email=email)
        email_activities = evaluation_user.email_activities

        if email_activities > 1:
            try:

                key = get_free_license_key(email)

                evaluation_user.email_activities = email_activities - 1
                evaluation_user.save()

                send_mail_customer(email, key, name)
                send_mail_admin(name, email, phone_number, company_name,
                                license_requirements, product_interest, time_frame, note_use)

                return JsonResponse({
                    'status': 'ok',
                    'message': 'An evaluation key has been emailed to you! '
                               'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                               'for technical assistance and licensing questions.',
                })
            except ValueError:
                return JsonResponse({
                    'status': 'failed',
                    'message': 'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                               'for assistance or questions with your evaluation.',
                })
        else:
            return JsonResponse({
                'status': 'failed',
                'message': 'This e-mail address already been used to register an evaluation. '
                           'Please contact info@openalpr.com to request an extension on your previous evaluation.',
            })

    else:

        try:
            key = get_free_license_key(email)

            new_customer = Evaluation_User(
                name=name, email=email,
                company_name=company_name,
                phone_number=phone_number,
                license_requirements=license_requirements,
                interest_product=product_interest,
                time_frame=time_frame,
                note_use=note_use,
                is_subscribed=0
            )

            new_customer.save()

            send_mail_customer(email, key, name)
            send_mail_admin(name, email, phone_number, company_name,
                            license_requirements, product_interest, time_frame, note_use)

            return JsonResponse({
                'status': 'ok',
                'message': 'An evaluation key has been emailed to you! '
                           'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                           'for technical assistance and licensing questions.',
            })
        except ValueError:
            return JsonResponse({
                'status': 'failed',
                'message': 'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                           'for assistance or questions with your evaluation.',
            })

def auth_key_generate_ajax(request):
    allowed_product_id = request.GET.get('allowed_product_id')
    email = request.user.email
    system_id = request.GET.get('system_id')
    license_register= request.GET.get('license_register')

    try:
        allowed_product = License_Allowance.objects.get(id=allowed_product_id)

        product_id = allowed_product.product_id

        product = Product.objects.get(id=product_id)

        product_name = product.name
        product_type = product.type

        key = get_auth_license_key(system_id, license_register, product_type)

        new_license = License_Registration(
            key=key,
            user_email=email,
            system_hash=system_id,
            number_licenses=license_register,
            product_id=allowed_product_id,
            product_name=product_name,
        )

        new_license.save()

        allowed_product = License_Allowance.objects.get(id=allowed_product_id)
        allowed_product.registered_product = int(allowed_product.registered_product) + int(license_register)
        allowed_product.save()

        send_mail_admin_register(
            email=email,
            product_name=product_name,
            key=key,
            system_hash=system_id,
            licenses_register=license_register,
        )

        return JsonResponse({
            'status': 'ok',
            'message': 'An evaluation key has been registered! '
                       'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                       'for technical assistance and licensing questions.',
        })
    except ValueError:
        return JsonResponse({
            'status': 'failed',
            'message': 'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                       'for assistance or questions with your evaluation.',
        })

def product_license_detail(request, product_id):

    licenses = License_Registration.objects.filter(product_id=product_id, user_email=request.user.email)
    allowed_product = License_Allowance.objects.get(id=product_id)
    product_id = allowed_product.product_id
    product = Product.objects.get(id=product_id)
    product_name = product.name

    context = {
        'product_name': product_name,
        'licenses': licenses,
    }

    return render(request, 'pages/product_license_detail.html', context)

def auth_key_register(request):

    if not request.user.is_authenticated():
        return redirect('main:login')

    user_id = request.user.id
    allowed_products = License_Allowance.objects.filter(user_id=user_id)

    for allowed_product in allowed_products:
        product_id = allowed_product.product_id
        product = Product.objects.get(id=product_id)
        product_name = product.name
        allowed_product.product_name = product_name

    context = {
        'allowed_products': allowed_products
    }
    return render(request, 'pages/license_register.html', context)

def chunkstring(string, length):

    return (string[0+i:length+i] for i in range(0, len(string), length))

def send_mail_customer(email, key, name):
    subject = "OpenALPR License Key"
    to = [email]
    from_email = 'info@openalpr.com'

    ctx = {
        'license_key': key,
        'first_name': name
    }

    message = get_template('email_template_customer_body.html').render(Context(ctx))
    msg = EmailMessage(subject, message, to=to, from_email=from_email)
    msg.content_subtype = 'html'
    msg.send()

def send_mail_admin(name, email, phone_number, company_name,
                    license_requirements, product_interest, time_frame, note_use):
    subject = "OpenALPR License Key"
    to = admin_emails
    from_email = 'info@openalpr.com'

    ctx = {
        'first_name': name,
        'email': email,
        'phone_number': phone_number,
        'company_name': company_name,
        'license_requirements': license_requirements,
        'product_interest': product_interest,
        'note_use': note_use,
        'time_frame': time_frame
    }

    message = get_template('email_template_admin_body.html').render(Context(ctx))
    msg = EmailMessage(subject, message, to=to, from_email=from_email)
    msg.content_subtype = 'html'
    msg.send()

def send_mail_admin_register(email, key, product_name,
                    licenses_register, system_hash):
    subject = "OpenALPR License Key"
    to = admin_emails
    from_email = 'info@openalpr.com'

    ctx = {
        'email': email,
        'key': key,
        'product_name': product_name,
        'licenses_register': licenses_register,
        'system_hash': system_hash,
    }

main/templates/pages/license_register.html
{% extends 'base.html' %}

{% load static %}
{% load template_variable_math %}

{% block title %}Auth Register License{% endblock %}

{% block content %}

    <div class="section register-form-section" style=" background-image: url({% static 'img/background.png' %}); background-position: top center; min-height: 700px;">
        <div class="container">

            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="card card-signup">
                        <form class="form auth-evaluation-register-form" method="post" action="">
                            {% csrf_token %}
                            <div class="header header-info text-center">
                                <h4>License Registration</h4>
                                <div class="social-line">
                                    <a href="https://www.facebook.com/openalpr" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-facebook-square"></i>
                                    </a>
                                    <a href="https://twitter.com/openalpr" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="https://www.linkedin.com/company/10472650/" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </div>
                            </div>

                            <div class="content">
                                <div class="row">
                                    <div class="col-md-offset-1 col-md-10">
                                        <table class="table auth_licenses_table">
                                            <thead>
                                                <tr>
                                                    <th class="text-left">Product</th>
                                                    <th class="text-left">Total</th>
                                                    <th class="text-left">Registered</th>
                                                    <th class="text-left">Available</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for allowed_product in allowed_products %}
                                                    <tr id="allowed_product_{{ allowed_product.id }}">
                                                        <td class="text-left"> <a href="{% url 'main:product_license_detail' product_id=allowed_product.id %}">{{ allowed_product.product_name }}</a></td>
                                                        <td>{{ allowed_product.total_product }}</td>
                                                        <td class="product_registered">{{ allowed_product.registered_product }}</td>
                                                        <td class="product_available">{{ allowed_product.total_product|template_variable_sum:allowed_product.registered_product }}</td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>

                            <p class="message text-divider col-md-12"></p>

                            <div class="content">

                                <div class="row">
                                    <div class="col-md-6 ">
                                        <select class="selectpicker allowed-product-dropdown" id="allowed_product"  name="allowed_product" data-style="btn btn-primary" title="Product License">
                                            <option disabled selected>Product License</option>
                                            {% for allowed_product in allowed_products %}
                                                <option value="{{ allowed_product.id }}">{{ allowed_product.product_name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>

                                    <div class="col-md-6" style="padding-top: 46px;">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                Available Licenses:
                                            </span>
                                            <span class="label label-info licenses_register_amount_text">N/A</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group label-floating system-id-form">
                                            <label class="control-label">System ID:</label>
                                            <input type="text" value="" class="form-control" name="system_id" id="system_id"/>
                                            <a rel="popover" class="form-control-feedback" data-toggle="popover" data-placement="right" title="Help Text" data-content="Run the 'openalpr-licenserequest' command on your system to generate a system ID">
                                                <i class="material-icons">notifications none</i>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                Licenses to Register:
                                            </span>
                                            <input type="number" class="form-control" id="license_register"  name="license_register" placeholder="Licenses to Register...">
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="footer text-center">
                                <button id="auth_key_generate_btn" class="btn btn-primary btn-lg register-btn">Register</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block additional_scripts %}
    <script type="text/javascript">
        var auth_key_generate_ajax_url = "{% url 'main:auth_key_generate_ajax' %}";
    </script>

    <script src="{% static 'js/main/auth_key_generate_ajax.js' %}" type="text/javascript"></script>
{% endblock %}

main/templates/pages/login.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}Register License{% endblock %}

{% block additional_styles %}

{% endblock %}

{% block content %}

    <div class="section" style=" background-image: url({% static 'img/background.png' %}); background-position: top center; min-height: 700px;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="card card-signup">
                        <form class="form login-form" role="form" method="post" action="{% url 'main:login' %}">

                            {% csrf_token %}

                            <div class="header header-info text-center">
                                <h4>LOGIN</h4>
                                <div class="social-line">
                                    <a href="https://www.facebook.com/openalpr" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-facebook-square"></i>
                                    </a>
                                    <a href="https://twitter.com/openalpr" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                    <a href="https://www.linkedin.com/company/10472650/" class="btn btn-simple btn-just-icon">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </div>
                            </div>

                            <p class="text-divider">Please provide your e-mail and password to register license.</p>

                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <p class="text-divider">
                                            <div class="alert alert-danger">
                                                <div class="container-fluid">
                                                    <div class="alert-icon">
                                                        <i class="material-icons">error_outline</i>
                                                    </div>
                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                        <span aria-hidden="true"><i class="material-icons">clear</i></span>
                                                    </button>
                                                    <b>Error:</b> {{ error|escape }}
                                                </div>
                                            </div>
                                        </p>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <p class="text-divider">
                                        <div class="alert alert-danger">
                                            <div class="container-fluid">
                                                <div class="alert-icon">
                                                    <i class="material-icons">error_outline</i>
                                                </div>
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true"><i class="material-icons">clear</i></span>
                                                </button>
                                                <b>Error:</b> {{ error|escape }}
                                            </div>
                                        </div>
                                    </p>
                                {% endfor %}
                            {% endif %}

                            <div class="content">

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">email</i>
                                            </span>
                                            {% for error in form.username.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                            {% render_field form.username tabindex="1" id="username" %}
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="input-group">
                                            <span class="input-group-addon">
                                                <i class="material-icons">lock</i>
                                            </span>
                                            {% for error in form.password.errors %}
                                                <div class="alert alert-danger">
                                                    <strong>{{ error|escape }}</strong>
                                                </div>
                                            {% endfor %}
                                            {% render_field form.password tabindex="2" id="password" %}
                                        </div>
                                    </div>
                                </div>

                                {% render_field form.next_ %}

                            </div>

                            <p class="text-divider">You can get 14 Day free license key <a href="{% url 'main:free_key_generate' %}">here</a>.</p>

                            <div class="footer text-center">
                                <button type="submit" name="login" id="login-submit" tabindex="4" class="btn btn-primary" value="Log In" style="margin-top: 50px; margin-bottom: 25px;">Login</button>
                            </div>

                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block additional_scripts %}

{% endblock %}