licensing_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from main import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^', include(urls, namespace='main'), name='main'),
]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^free_key_generate/', views.free_key_generate, name='free_key_generate'),
    url(r'^free_key_generate_ajax/', views.free_key_generate_ajax, name='free_key_generate_ajax'),
    url(r'^auth_key_register/', views.auth_key_register, name='auth_key_register'),
    url(r'^auth_key_generate_ajax/', views.auth_key_generate_ajax, name='auth_key_generate_ajax'),
    url(r'^product_license_detail/(?P<product_id>[0-9]+)/$', views.product_license_detail, name='product_license_detail'),
    url(r'^logout/$', views.logout, name='logout'),
]

main/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin

# Create your models here.

class AuthUserManager(BaseUserManager):
    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        if not email:
            raise ValueError('The given email must be set')

        email = self.normalize_email(email)
        user = self.model(email=email, is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)

class Customer(AbstractBaseUser, PermissionsMixin):
    """
    Used for all authenticated user (influencers, brands, assistants, superuser, etc...)
    """

    first_name = models.CharField( ('first name'), max_length=30, blank=True)
    last_name = models.CharField( ('last name'), max_length=30, blank=True)
    email = models.EmailField( ('email address'), max_length=254, unique=True)
    is_staff = models.BooleanField( ('staff status'), default=False,
                                   help_text= ('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField( ('active'), default=True,
                                    help_text= ('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField( ('date joined'), auto_now_add=True)
    objects = AuthUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __unicode__(self):
        return self.email

    class Meta:
        db_table = 'customer'

class Evaluation_User(models.Model):

    name = models.CharField(max_length=30, db_column="name")
    email = models.EmailField(max_length=254, unique=True, db_column="email")
    company_name = models.CharField(max_length=255, db_column="company_name", default="")
    phone_number = models.CharField(max_length=255, db_column="phone_number", default="")
    license_requirements = models.CharField(max_length=255, db_column="license_requirements", default="")
    interest_product = models.CharField(max_length=255, db_column="interest_product", default="")
    time_frame = models.CharField(max_length=255, db_column="time_frame", default="")
    date_joined = models.DateTimeField(auto_now_add=True, db_column="date_joined")
    is_subscribed = models.BooleanField(default=False, db_column="is_subscribed")
    note_use = models.TextField(db_column="note_use", default="")
    email_activities = models.IntegerField(max_length=11, db_column="email_activities", default=1)

    class Meta:
        db_table = 'evaluation_user'

class Label_License_Requirement(models.Model):

    list_id = models.IntegerField(max_length=30, db_column="list_id")
    name = models.CharField(max_length=30, db_column="name")

    class Meta:
        db_table = 'label_license_requirement'

class Label_Interest_Product(models.Model):
    list_id = models.IntegerField(max_length=30, db_column="list_id")
    name = models.CharField(max_length=30, db_column="name")

    class Meta:
        db_table = 'label_interest_product'

class Label_Purchase_Time_Frame(models.Model):

    list_id = models.IntegerField(max_length=30, db_column="list_id")
    name = models.CharField(max_length=30, db_column="name")

    class Meta:
        db_table = 'label_purchase_time_frame'

class License_Allowance(models.Model):

    product_id = models.IntegerField(max_length=11, db_column="product_id", default=0)
    user_id = models.IntegerField(max_length=11, db_column="user_id", default=0)
    total_product = models.CharField(max_length=30, db_column="total_product", default=0)
    registered_product = models.CharField(max_length=30, db_column="registered_product", default=0)

    class Meta:
        db_table = 'license_allowance'

class License_Registration(models.Model):

    key = models.TextField(max_length=30, db_column="key")
    product_id = models.EmailField(max_length=254, db_column="product_id")
    user_email = models.CharField(max_length=254, db_column="user_email")
    system_hash = models.CharField(max_length=254, db_column="system_hash")
    product_name = models.CharField(max_length=254, db_column="product_name", default="")
    number_licenses = models.IntegerField(max_length=11, db_column="number_licenses")
    date_joined = models.DateTimeField(('date joined'), auto_now_add=True)

    class Meta:
        db_table = 'license_registration'

class Product(models.Model):

    name = models.CharField(max_length=254, db_column="name")
    type = models.CharField(max_length=254, db_column="type", default="")

    class Meta:
        db_table = 'product'

main/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms

invalid_error = 'User with this {} already exists.'

class LoginForm(auth_forms.AuthenticationForm):
    username = forms.EmailField(max_length=254,
                               widget=forms.EmailInput(attrs={'class': 'form-control',
                                                             'required': 'Trcue',
                                                              'placeholder': 'Email...'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'required': 'True',
                                                                 'placeholder': 'Password...'}))
    next_ = forms.CharField(widget=forms.HiddenInput())

main/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login
from django.template import Context
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.conf import settings

from os.path import expanduser

from .models import *
from .forms import LoginForm

import subprocess
import time
import re

admin_emails = settings.ADMIN_EMAIL_LIST

# Create your views here.c

def login(request):
    redirect_to = request.POST.get('next_',
                                   request.GET.get('next', 'main:auth_key_register'))
    if request.user.is_authenticated():
        return redirect(redirect_to)
    if request.method == "POST":

        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            # Okay, security check complete. Log the user in.
            auth.login(request, form.get_user())
            return redirect(redirect_to)
    else:
        form = LoginForm(request, initial={'next_': redirect_to})

    return render(request, 'pages/login.html', {'form': form})

def logout(request):
    auth.logout(request)
    return redirect('main:login')

def free_key_generate(request):

    license_requirements_list = Label_License_Requirement.objects.all()
    interest_products_list = Label_Interest_Product.objects.all()
    time_frame_list = Label_Purchase_Time_Frame.objects.all()

    context = {
        'license_requirements_list': license_requirements_list,
        'interest_products_list': interest_products_list,
        'time_frame_list': time_frame_list,
    }

    return render(request, 'pages/eval_request.html', context)

def free_key_generate_ajax(request):

    name = request.GET.get('name')
    email = request.GET.get('email')
    company_name = request.GET.get('company_name')
    phone_number = request.GET.get('phone_number')
    note_use = request.GET.get('note_use')
    license_requirements = request.GET.get('license_requirements')
    product_interest = request.GET.get('product_interest')
    time_frame = request.GET.get('time_frame')

    if Evaluation_User.objects.filter(email=email).exists():

        evaluation_user = Evaluation_User.objects.get(email=email)
        email_activities = evaluation_user.email_activities

        if email_activities > 1:
            try:

                key = get_free_license_key(email)

                evaluation_user.email_activities = email_activities - 1
                evaluation_user.save()

                send_mail_customer(email, key, name)
                send_mail_admin(name, email, phone_number, company_name,
                                license_requirements, product_interest, time_frame, note_use)

                return JsonResponse({
                    'status': 'ok',
                    'message': 'An evaluation key has been emailed to you! '
                               'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                               'for technical assistance and licensing questions.',
                })
            except ValueError:
                return JsonResponse({
                    'status': 'failed',
                    'message': 'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                               'for assistance or questions with your evaluation.',
                })
        else:
            return JsonResponse({
                'status': 'failed',
                'message': 'This e-mail address already been used to register an evaluation. '
                           'Please contact info@openalpr.com to request an extension on your previous evaluation.',
            })

    else:

        try:
            key = get_free_license_key(email)

            new_customer = Evaluation_User(
                name=name, email=email,
                company_name=company_name,
                phone_number=phone_number,
                license_requirements=license_requirements,
                interest_product=product_interest,
                time_frame=time_frame,
                note_use=note_use,
                is_subscribed=0
            )

            new_customer.save()

            send_mail_customer(email, key, name)
            send_mail_admin(name, email, phone_number, company_name,
                            license_requirements, product_interest, time_frame, note_use)

            return JsonResponse({
                'status': 'ok',
                'message': 'An evaluation key has been emailed to you! '
                           'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                           'for technical assistance and licensing questions.',
            })
        except ValueError:
            return JsonResponse({
                'status': 'failed',
                'message': 'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                           'for assistance or questions with your evaluation.',
            })

def auth_key_generate_ajax(request):
    allowed_product_id = request.GET.get('allowed_product_id')
    email = request.user.email
    system_id = request.GET.get('system_id')
    license_register= request.GET.get('license_register')

    try:
        allowed_product = License_Allowance.objects.get(id=allowed_product_id)

        product_id = allowed_product.product_id

        product = Product.objects.get(id=product_id)

        product_name = product.name
        product_type = product.type

        key = get_auth_license_key(system_id, license_register, product_type)

        new_license = License_Registration(
            key=key,
            user_email=email,
            system_hash=system_id,
            number_licenses=license_register,
            product_id=allowed_product_id,
            product_name=product_name,
        )

        new_license.save()

        allowed_product = License_Allowance.objects.get(id=allowed_product_id)
        allowed_product.registered_product = int(allowed_product.registered_product) + int(license_register)
        allowed_product.save()

        send_mail_admin_register(
            email=email,
            product_name=product_name,
            key=key,
            system_hash=system_id,
            licenses_register=license_register,
        )

        return JsonResponse({
            'status': 'ok',
            'message': 'An evaluation key has been registered! '
                       'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                       'for technical assistance and licensing questions.',
        })
    except ValueError:
        return JsonResponse({
            'status': 'failed',
            'message': 'Please <a href="http://www.openalpr.com/contact-us.html"> Contact-Us </a> '
                       'for assistance or questions with your evaluation.',
        })

def product_license_detail(request, product_id):

    licenses = License_Registration.objects.filter(product_id=product_id, user_email=request.user.email)
    allowed_product = License_Allowance.objects.get(id=product_id)
    product_id = allowed_product.product_id
    product = Product.objects.get(id=product_id)
    product_name = product.name

    context = {
        'product_name': product_name,
        'licenses': licenses,
    }

    return render(request, 'pages/product_license_detail.html', context)

def auth_key_register(request):

    if not request.user.is_authenticated():
        return redirect('main:login')

    user_id = request.user.id
    allowed_products = License_Allowance.objects.filter(user_id=user_id)

    for allowed_product in allowed_products:
        product_id = allowed_product.product_id
        product = Product.objects.get(id=product_id)
        product_name = product.name
        allowed_product.product_name = product_name

    context = {
        'allowed_products': allowed_products
    }
    return render(request, 'pages/license_register.html', context)

def chunkstring(string, length):

    return (string[0+i:length+i] for i in range(0, len(string), length))

def send_mail_customer(email, key, name):
    subject = "OpenALPR License Key"
    to = [email]
    from_email = 'info@openalpr.com'

    ctx = {
        'license_key': key,
        'first_name': name
    }

    message = get_template('email_template_customer_body.html').render(Context(ctx))
    msg = EmailMessage(subject, message, to=to, from_email=from_email)
    msg.content_subtype = 'html'
    msg.send()

def send_mail_admin(name, email, phone_number, company_name,
                    license_requirements, product_interest, time_frame, note_use):
    subject = "OpenALPR License Key"
    to = admin_emails
    from_email = 'info@openalpr.com'

    ctx = {
        'first_name': name,
        'email': email,
        'phone_number': phone_number,
        'company_name': company_name,
        'license_requirements': license_requirements,
        'product_interest': product_interest,
        'note_use': note_use,
        'time_frame': time_frame
    }

    message = get_template('email_template_admin_body.html').render(Context(ctx))
    msg = EmailMessage(subject, message, to=to, from_email=from_email)
    msg.content_subtype = 'html'
    msg.send()

def send_mail_admin_register(email, key, product_name,
                    licenses_register, system_hash):
    subject = "OpenALPR License Key"
    to = admin_emails
    from_email = 'info@openalpr.com'

    ctx = {
        'email': email,
        'key': key,
        'product_name': product_name,
        'licenses_register': licenses_register,
        'system_hash': system_hash,
    }

main/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png">
	<link rel="icon" type="image/png" href="{% static 'favicon.ico' %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>{% block title %}{% endblock %} - License Generator - openALPR Platform</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

	<!--     Fonts and icons     -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	<!-- CSS Files -->
    <link href="{%static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{%static 'css/bootstrap-select.css' %}" rel="stylesheet" />
    <link href="{%static 'css/material-kit.css' %}" rel="stylesheet" />

    <link href="{%static 'css/demo.css' %}" rel="stylesheet" />

    {% block additional_styles %}{% endblock %}
</head>

<body class="index-page">
<!-- Navbar -->
<nav class="navbar navbar-fixed-top navbar-openalpr navbar-info">
	<div class="container">
        <div class="navbar-header">
	    	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-index">
	        	<span class="sr-only">Toggle navigation</span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	    	</button>
	    	<a href="" class="effect-shine">
	        	<div class="logo-container">
	                <div class="logo">
	                    <img src="{% static 'img/logo_whiteonly.svg' %}" alt="openALPR License Generator Logo" rel="tooltip" title="<b>openALPR License Generator</b>" data-placement="bottom" data-html="true">
	                </div>
	                <div class="brand">
	                    License
	                </div>
				</div>
	      	</a>
	    </div>

	    <div class="collapse navbar-collapse" id="navigation-index">
	    	<ul class="nav navbar-nav navbar-right">
				<li>
                    {% if request.user.is_authenticated %}
                        <a rel="tooltip" title="Logout" data-placement="bottom" href="{% url 'main:logout' %}" class="btn btn-white btn-simple btn-just-icon">
                            <i class="fa fa-user-circle"></i>
                        </a>
                    {% else %}
                        <a rel="tooltip" title="Login" data-placement="bottom" href="{% url 'main:login' %}" class="btn btn-white btn-simple btn-just-icon">
                            <i class="fa fa-user-circle"></i>
                        </a>
                    {% endif %}
				</li>
	    	</ul>
	    </div>
	</div>
</nav>
<!-- End Navbar -->

<div class="wrapper">

	<div class="main main-raised" style="margin-top: 0px; padding-top: 70px;">
		{% block content %}{% endblock %}
	</div>

    <footer class="footer">
	    <div class="container">
	        <nav class="pull-left">
	            <ul>

	            </ul>
	        </nav>
	        <div class="copyright pull-right">
	            Copyright &copy; by openALPR License 2017. All right reserved.
	        </div>
	    </div>
	</footer>
</div>

</body>

	<!--   Core JS Files   -->
	<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/material.min.js' %}" type="text/javascript"></script>

    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
	<script src="{% static 'js/bootstrap-selectpicker.js' %}" type="text/javascript"></script>

	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
	<script src="{% static 'js/material-kit.js' %}" type="text/javascript"></script>

    {% block additional_scripts %}{% endblock %}

</html>

main/templates/email_template.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8"> <!-- utf-8 works for most cases -->
    <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldn't be necessary -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
    <meta name="x-apple-disable-message-reformatting">  <!-- Disable auto-scale in iOS 10 Mail entirely -->
    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->

    <!-- Web Font / @font-face : BEGIN -->
	<!-- NOTE: If web fonts are not required, lines 10 - 27 can be safely removed. -->

    <!-- Desktop Outlook chokes on web font references and defaults to Times New Roman, so we force a safe fallback font. -->
    <!--[if mso]>
        <style>
            * {
                font-family: sans-serif !important;
            }
        </style>
    <![endif]-->

    <!-- All other clients get the webfont reference; some will render the font and others will silently fail to the fallbacks. More on that here: http://stylecampaign.com/blog/2015/02/webfont-support-in-email/ -->
    <!--[if !mso]><!-->
        <!-- insert web font reference, eg: <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'> -->
    <!--<![endif]-->

    <!-- Web Font / @font-face : END -->

      <!-- CSS Reset -->
    <style>

        /* What it does: Remove spaces around the email design added by some email clients. */
        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
        html,
        body {
            margin: 0 auto !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }

        /* What it does: Stops email clients resizing small text. */
        * {
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        /* What is does: Centers email on Android 4.4 */
        div[style*="margin: 16px 0"] {
            margin:0 !important;
        }

        /* What it does: Stops Outlook from adding extra spacing to tables. */
        table,
        td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }

        /* What it does: Fixes webkit padding issue. Fix for Yahoo mail table alignment bug. Applies table-layout to the first 2 tables then removes for anything nested deeper. */
        table {
            border-spacing: 0 !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            margin: 0 auto !important;
        }
        table table table {
            table-layout: auto;
        }

        /* What it does: Uses a better rendering method when resizing images in IE. */
        img {
            -ms-interpolation-mode:bicubic;
        }

        /* What it does: A work-around for iOS meddling in triggered links. */
        .mobile-link--footer a,
        a[x-apple-data-detectors] {
            color:inherit !important;
            text-decoration: underline !important;
        }

        /* What it does: Prevents underlining the button text in Windows 10 */
        .button-link {
            text-decoration: none !important;
        }

    </style>

    <!-- Progressive Enhancements -->
    <style>

        /* What it does: Hover styles for buttons */
        .button-td,
        .button-a {
            transition: all 100ms ease-in;
        }
        .button-td:hover,
        .button-a:hover {
            background: #555555 !important;
            border-color: #555555 !important;
        }

    </style>

</head>
<body width="100%" bgcolor="#ffffff" style="margin: 0; mso-line-height-rule: exactly;">
    <center style="width: 100%; background: #ffffff;">

        <!-- Visually Hidden Preheader Text : BEGIN -->
        <div style="display:none;font-size:1px;line-height:1px;max-height:0px;max-width:0px;opacity:0;overflow:hidden;mso-hide:all;font-family: sans-serif;">
            (Optional) This text will appear in the inbox preview, but not the email body.
        </div>
        <!-- Visually Hidden Preheader Text : END -->

        <!--
            Set the email width. Defined in two places:
            1. max-width for all clients except Desktop Windows Outlook, allowing the email to squish on narrow but never go wider than 600px.
            2. MSO tags for Desktop Windows Outlook enforce a 600px width.
        -->
        <div style="max-width: 600px; margin: auto;">
            <!--[if mso]>
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="600" align="center">
            <tr>
            <td>
            <![endif]-->


            <!-- Email Body : BEGIN -->
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 600px;">

                <!-- Hero Image, Flush : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <img src="http://www.openalpr.com/assets/images/email/email_banner.png" width="600" height="" alt="OpenALPR" border="0" align="center" style="width: 100%; max-width: 600px; height: auto; background: #ffffff; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                    </td>
                </tr>
                <!-- Hero Image, Flush : END -->

                <!-- 1 Column Text + Button : BEGIN -->
                <tr>
                    <td bgcolor="#ffffff">
                        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
                            <tr>
                                <td style="padding: 40px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">

                                    {% block body %}{% endblock %}

                                </td>
                                </tr>
                        </table>
                    </td>
                </tr>
                <!-- 1 Column Text + Button : BEGIN -->


                <!-- Clear Spacer : BEGIN -->
                <tr>
                    <td height="40" style="font-size: 0; line-height: 0;">
                        &nbsp;
                    </td>
                </tr>
                <!-- Clear Spacer : END -->


            </table>
            <!-- Email Body : END -->

            <!-- Email Footer : BEGIN -->
            <table role="presentation" cellspacing="0" cellpadding="0" border="0" align="center" width="100%" style="max-width: 680px;">
                <tr>
                    <td style="padding: 40px 10px;width: 100%;font-size: 12px; font-family: sans-serif; line-height:18px; text-align: center; color: #888888;">


                        OpenALPR Technology, Inc.<br><span class="mobile-link--footer">1-800-935-1699</span>
                        <br><br>


                    </td>
                </tr>
            </table>
            <!-- Email Footer : END -->

            <!--[if mso]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </div>
    </center>
</body>
</html>

main/templates/email_template_admin_body.html
{% extends "email_template.html" %}
{% block body %}
    <p>Name: {{ first_name }}</p>
    <p>Email: {{email}}</p>
    <p>Phone Number: {{phone_number}}</p>
    <p>Company: {{company_name}}</p>
    <p>Projected License Requirements: {{license_requirements}}</p>
    <p>Interest Product: {{product_interest}}</p>
    <p>Purchase Time Frame: {{time_frame}}</p>
    <p>Note: {{note_use}}</p>
{% endblock %}

main/templates/email_template_admin_register_body.html
{% extends "email_template.html" %}
{% block body %}
    <p>Email: {{email}}</p>
    <p>Key: {{key}}</p>
    <p>Product Name: {{product_name}}</p>
    <p>Licenses to Register: {{licenses_register}}</p>
    <p>System Hash: {{system_hash}}</p>
{% endblock %}

main/templates/email_template_customer_body.html
{% extends "email_template.html" %}
{% block body %}
    <p>{{ first_name }},</p>
    <p>We are excited to help you begin your test drive of OpenALPR software.  Please find your 14-day evaluation code below:</p>
        <p>{{license_key}}</p>

    <p>Visit <a href="http://doc.openalpr.com/">doc.openalpr.com</a> for the download links and installation instructions for the product you're interested in.</p>
    <p>If you have any questions, don't hesitate to e-mail <a href="mailto:info@openalpr.com">info@openalpr.com</a>.</p>

{% endblock %}